variable "aws_region" { default = "us-east-1" }
variable "project_name" { default = "new-infra-3-tier" }
variable "vpc_cidr" { default = "10.0.0.0/16" }
variable "public_subnets" { default = ["10.0.1.0/24", "10.0.2.0/24"] }
variable "private_subnets" { default = ["10.0.101.0/24", "10.0.102.0/24"] }
variable "instance_type" { default = "t3.micro" }
variable "asg_desired" { default = 2 }
variable "admin_cidr" { default = "0.0.0.0/0" }
variable "db_username" { default = "dbadmin" }
variable "db_password" { default = "Password123!" }
variable "db_allocated_storage" { default = 20 }
